name: reposearch
description: "GitHub repository search app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mobx:
  flutter_mobx:
  get_it: ^7.2.0
  shared_preferences: ^2.0.20
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.5
  intl: ^0.19.0
  http: ^0.13.5
  url_launcher: ^6.3.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/
    - assets/langs/